spring:
  data:
    mongodb:
      uri: mongodb+srv://customeradmin:customerportal@cluster0.wbfea.mongodb.net/?retryWrites=true
      database: customer_test_quintrix
  security:
    user:
      name: root
      password: toor

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.quintrix: DEBUG
