spring:
  data:
    mongodb:
      uri: mongodb+srv://customeradmin:customerportal@cluster0.wbfea.mongodb.net/?retryWrites=true
      database: customer_test_quintrix
    oauth2:
      client:
        registration:
          google:
            client-id: <ID>
            client-secret: <SECRET>